import esbuild from "esbuild";
import { cp, mkdir } from "node:fs/promises";
import process from "node:process";
import { builtinModules } from "node:module";
import { join } from "node:path";

const production = process.argv[2] === "production";
const pluginId = "daily-saying-kr";
const vaultPath = process.env.OBSIDIAN_VAULT_PATH;

if (!production && !vaultPath) {
  console.error("OBSIDIAN_VAULT_PATH is required for npm run dev.");
  console.error('Example: OBSIDIAN_VAULT_PATH="/absolute/path/to/your-vault" npm run dev');
  process.exit(1);
}

const pluginDir = vaultPath
  ? join(vaultPath, ".obsidian", "plugins", pluginId)
  : null;

async function deployDevArtifacts() {
  if (!pluginDir) {
    return;
  }

  await mkdir(pluginDir, { recursive: true });

  for (const file of ["main.js", "manifest.json", "versions.json"]) {
    await cp(file, join(pluginDir, file));
  }

  console.log(`Deployed ${pluginId} to:`);
  console.log(`  ${pluginDir}`);
}

const context = await esbuild.context({
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: production
    ? []
    : [
        {
          name: "deploy-dev-artifacts",
          setup(build) {
            build.onEnd(async (result) => {
              if (result.errors.length === 0) {
                await deployDevArtifacts();
              }
            });
          },
        },
      ],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
